import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { getShape, shapeNames } from "../src/core/material-shapes";
import { toClipPathPolygon } from "../src/output/clip-path";

const toKebab = (name: string): string =>
  name
    .replace(/([a-z])(\d)/g, "$1-$2")
    .replace(/(\d)([A-Z])/g, "$1-$2")
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .toLowerCase();

const lines: string[] = [
  "/* Generated by shape-morph. Do not edit. */",
  "/* A package by Thereallo */",
  "/* https://github.com/thereallo/shape-morph */",
  "/* MIT License */",
  "",
];

for (const name of shapeNames) {
  const shape = getShape(name);
  const polygon = toClipPathPolygon(shape.cubics);
  const kebab = toKebab(name);

  lines.push(`@utility clip-${kebab} {`);
  lines.push(`  clip-path: ${polygon};`);
  lines.push("}", "");
}

const outPath = join(import.meta.dirname, "..", "dist", "tailwind.css");
writeFileSync(outPath, lines.join("\n"));

console.log(`Generated ${shapeNames.length} utilities → ${outPath}`);
